#!/bin/bash

# Get the current directory
current_dir="$(cd "$(dirname "$0")" && pwd)"

# Check if the first argument is "install" and run npm install
if [ "$1" = "install" ]; then
    npm install
    tsc
elif [ "$1" = "test" ]; then
    npx jest
else
    # Navigate to the /dist folder and execute index.js
    cd "$current_dir/dist" || exit
    # Execute your TypeScript CLI program
    node index.js "$@"
fi
