name: CD - AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Set your AWS region

    - name: Deploy AWS Lambda function
      run: |
        sam build
        sam deploy --stack-name <stack-name> --s3-bucket <your-s3-bucket> --region <region> --capabilities CAPABILITY_IAM

