name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh-keyscan -H $HOST_DNS >> ~/.ssh/known_hosts
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_DNS: ${{ secrets.HOST_DNS }}

    - name: Deploy code to EC2
      run: |
        ssh -i deploy_key.pem $vaibhavturaga@$HOST_DNS "cd $TARGET_DIR && git pull https://vaibhavturaga:TOKEN@github.com/vaibhavturaga/ECE461-Part-2.git main"
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_DNS: ${{ secrets.HOST_DNS }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.PAT }} # Make sure you have this secret defined in your GitHub repository settings
